module.exports = {
  env: {
    CONTENTFUL_SPACE_ID: process.env.CONTENTFUL_SPACE_ID,
    CONTENTFUL_ACCESS_TOKEN: process.env.CONTENTFUL_ACCESS_TOKEN,
    NEXT_PUBLIC_GOOGLE_FORM_URL: process.env.NEXT_PUBLIC_GOOGLE_FORM_URL,
    NEXT_PUBLIC_GOOGLE_FORM_ENTRY_NAME: process.env.NEXT_PUBLIC_GOOGLE_FORM_ENTRY_NAME,
    NEXT_PUBLIC_GOOGLE_FORM_ENTRY_EMAIL: process.env.NEXT_PUBLIC_GOOGLE_FORM_ENTRY_EMAIL,
    NEXT_PUBLIC_GOOGLE_FORM_ENTRY_MESSAGE: process.env.NEXT_PUBLIC_GOOGLE_FORM_ENTRY_MESSAGE,
  },
};
